In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from avaml.aggregatedata import ForecastDataset, LabeledData, REG_ENG, CsvMissingError

# Read in data

In [2]:
model_prefix = ''
days = 7
regobs_types = list(REG_ENG.keys())
labeled_data = None
try:
    print("Reading csv")
    labeled_data = LabeledData.from_csv(days=days, regobs_types=regobs_types, with_varsom=True)
except CsvMissingError:
    print("Csv missing. Fetching online data. (This takes a long time.)")
    labeled_data = ForecastDataset(regobs_types=regobs_types).label(days=days, with_varsom=True)
    labeled_data.to_csv()

Reading csv

# EDA

In [3]:
labeled_data

In [4]:
vars(labeled_data).keys()

dict_keys(['data', 'row_weight', 'label', 'pred', 'days', 'with_varsom', 'regobs_types', 'single', 'seasons'])

In [5]:
vars(labeled_data)

{'data':                 region_id_3001 region_id_3002 region_id_3003 region_id_3004  \
                              0              0              0              0
 2017-12-07 3003            0.0            0.0            1.0            0.0
            3007            0.0            0.0            0.0            0.0
            3009            0.0            0.0            0.0            0.0
            3010            0.0            0.0            0.0            0.0
            3011            0.0            0.0            0.0            0.0
 ...                        ...            ...            ...            ...
 2021-01-12 3031            0.0            0.0            0.0            0.0
            3032            0.0            0.0            0.0            0.0
            3034            0.0            0.0            0.0            0.0
            3035            0.0            0.0            0.0            0.0
            3037            0.0            0.0            0.0            0.0

                 region_id_3005 region_id_3006 region_id_3007 region_id_3008  \
                              0              0              0              0
 2017-12-07 3003            0.0            0.0            0.0            0.0
            3007            0.0            0.0            1.0            0.0
            3009            0.0            0.0            0.0            0.0
            3010            0.0            0.0            0.0            0.0
            3011            0.0            0.0            0.0            0.0
 ...                        ...            ...            ...            ...
 2021-01-12 3031            0.0            0.0            0.0            0.0
            3032            0.0            0.0            0.0            0.0
            3034            0.0            0.0            0.0            0.0
            3035            0.0            0.0            0.0            0.0
            3037            0.0            0.0            0.0            0.0

                 region_id_3009 region_id_3010  ... regobs_snowprofile_t_min_4  \
                              0              0  ...                          4
 2017-12-07 3003            0.0            0.0  ...                        0.0
            3007            0.0            0.0  ...                        0.0
            3009            1.0            0.0  ...                        0.0
            3010            0.0            1.0  ...                        0.0
            3011            0.0            0.0  ...                        0.0
 ...                        ...            ...  ...                        ...
 2021-01-12 3031            0.0            0.0  ...                        0.0
            3032            0.0            0.0  ...                        0.0
            3034            0.0            0.0  ...                        0.0
            3035            0.0            0.0  ...                        0.0
            3037            0.0            0.0  ...                        0.0

                                accuracy
                    5    6    7        2    3    4    5    6    7
 2017-12-07 3003  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3007  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3009  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3010  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3011  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
 ...              ...  ...  ...      ...  ...  ...  ...  ...  ...
 2021-01-12 3031  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3032  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3034  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3035  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
            3037  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0

 [12651 rows x 6562 columns],
 'row_weight': 0           1
 2017-12-07  3003    1.0
             3007    1.0
             3009    1.0
             3010    1.0
             3011    1.0
                    ...
 2021-01-12  3031    1.0
             3032    1.0
             3034    1.0
             3035    1.0
             3037    1.0
 Name: 2, Length: 12651, dtype: float64,
 'label':                        CLASS                                            \

                 danger_level emergency_warning   problem_1   problem_2
 2017-12-07 3003            2         Ikke gitt  drift-slab
            3007            2         Ikke gitt    pwl-slab  drift-slab
            3009            2         Ikke gitt    pwl-slab  drift-slab
            3010            3         Ikke gitt  drift-slab    pwl-slab
            3011            3         Ikke gitt  drift-slab    pwl-slab
 ...                      ...               ...         ...         ...
 2021-01-12 3031            3         Ikke gitt    pwl-slab
            3032            3         Ikke gitt    pwl-slab
            3034            3         Ikke gitt    pwl-slab
            3035            3         Ikke gitt    pwl-slab
            3037            3         Ikke gitt    pwl-slab

                                                                          ...  \
                                          drift-slab                      ...
                 problem_3 problem_amount      cause dist dsize lev_fill  ...
 2017-12-07 3003                        1  snowdrift    1     2        1  ...
            3007                        2   new-snow    2     2        1  ...
            3009                        2   new-snow    2     2        1  ...
            3010                        2   new-snow    3     2        1  ...
            3011                        2   new-snow    3     2        1  ...
 ...                   ...            ...        ...  ...   ...      ...  ...
 2021-01-12 3031                        1          0    0     0        0  ...
            3032                        1          0    0     0        0  ...
            3034                        1          0    0     0        0  ...
            3035                        1          0    0     0        0  ...
            3037                        1          0    0     0        0  ...

                      REAL                                                      \
                 new-loose         new-slab         pwl-slab         wet-loose
                   lev_max lev_min  lev_max lev_min  lev_max lev_min   lev_max
 2017-12-07 3003       0.0     0.0      0.0     0.0      0.0     0.0       0.0
            3007       0.0     0.0      0.0     0.0    700.0   200.0       0.0
            3009       0.0     0.0      0.0     0.0    700.0   200.0       0.0
            3010       0.0     0.0      0.0     0.0    700.0   200.0       0.0
            3011       0.0     0.0      0.0     0.0    700.0   200.0       0.0
 ...                   ...     ...      ...     ...      ...     ...       ...
 2021-01-12 3031       0.0     0.0      0.0     0.0    600.0   600.0       0.0
            3032       0.0     0.0      0.0     0.0    800.0   800.0       0.0
            3034       0.0     0.0      0.0     0.0    600.0   600.0       0.0
            3035       0.0     0.0      0.0     0.0    800.0   800.0       0.0
            3037       0.0     0.0      0.0     0.0    800.0   800.0       0.0


                         wet-slab
                 lev_min  lev_max lev_min
 2017-12-07 3003     0.0      0.0     0.0
            3007     0.0      0.0     0.0
            3009     0.0      0.0     0.0
            3010     0.0      0.0     0.0
            3011     0.0      0.0     0.0
 ...                 ...      ...     ...
 2021-01-12 3031     0.0      0.0     0.0
            3032     0.0      0.0     0.0
            3034     0.0      0.0     0.0
            3035     0.0      0.0     0.0
            3037     0.0      0.0     0.0

 [12651 rows x 69 columns],
 'pred':                        CLASS                                                  \

                 danger_level emergency_warning problem_1 problem_2 problem_3
 2017-12-07 3003
            3007
            3009
            3010
            3011
 ...                      ...               ...       ...       ...       ...
 2021-01-12 3031
            3032
            3034
            3035
            3037

                                                                ...      REAL  \
                                drift-slab                      ... new-loose
                 problem_amount      cause dist dsize lev_fill  ...   lev_max
 2017-12-07 3003                         0    0     0        0  ...         0
            3007                         0    0     0        0  ...         0
            3009                         0    0     0        0  ...         0
            3010                         0    0     0        0  ...         0
            3011                         0    0     0        0  ...         0
 ...                        ...        ...  ...   ...      ...  ...       ...
 2021-01-12 3031                         0    0     0        0  ...         0
            3032                         0    0     0        0  ...         0
            3034                         0    0     0        0  ...         0
            3035                         0    0     0        0  ...         0
            3037                         0    0     0        0  ...         0

                                                                              \
                         new-slab         pwl-slab         wet-loose
                 lev_min  lev_max lev_min  lev_max lev_min   lev_max lev_min
 2017-12-07 3003       0        0       0        0       0         0       0
            3007       0        0       0        0       0         0       0
            3009       0        0       0        0       0         0       0
            3010       0        0       0        0       0         0       0
            3011       0        0       0        0       0         0       0
 ...                 ...      ...     ...      ...     ...       ...     ...
 2021-01-12 3031       0        0       0        0       0         0       0
            3032       0        0       0        0       0         0       0
            3034       0        0       0        0       0         0       0
            3035       0        0       0        0       0         0       0
            3037       0        0       0        0       0         0       0


                 wet-slab
                  lev_max lev_min
 2017-12-07 3003        0       0
            3007        0       0
            3009        0       0
            3010        0       0
            3011        0       0
 ...                  ...     ...
 2021-01-12 3031        0       0
            3032        0       0
            3034        0       0
            3035        0       0
            3037        0       0

 [12651 rows x 69 columns],
 'days': 7,
 'with_varsom': True,
 'regobs_types': ['Faretegn',
  'Tester',
  'Skredaktivitet',
  'Skredhendelse',
  'Snødekke',
  'Skredproblem',
  'Skredfarevurdering',
  'Snøprofil'],
 'single': False,
 'seasons': ['-', '0', '1', '2', '7', '8', '9']}

In [6]:
labeled_data.label

                       CLASS                                            \

                danger_level emergency_warning   problem_1   problem_2
2017-12-07 3003            2         Ikke gitt  drift-slab
           3007            2         Ikke gitt    pwl-slab  drift-slab
           3009            2         Ikke gitt    pwl-slab  drift-slab
           3010            3         Ikke gitt  drift-slab    pwl-slab
           3011            3         Ikke gitt  drift-slab    pwl-slab
...                      ...               ...         ...         ...
2021-01-12 3031            3         Ikke gitt    pwl-slab
           3032            3         Ikke gitt    pwl-slab
           3034            3         Ikke gitt    pwl-slab
           3035            3         Ikke gitt    pwl-slab
           3037            3         Ikke gitt    pwl-slab

                                                                         ...  \
                                         drift-slab                      ...
                problem_3 problem_amount      cause dist dsize lev_fill  ...
2017-12-07 3003                        1  snowdrift    1     2        1  ...
           3007                        2   new-snow    2     2        1  ...
           3009                        2   new-snow    2     2        1  ...
           3010                        2   new-snow    3     2        1  ...
           3011                        2   new-snow    3     2        1  ...
...                   ...            ...        ...  ...   ...      ...  ...
2021-01-12 3031                        1          0    0     0        0  ...
           3032                        1          0    0     0        0  ...
           3034                        1          0    0     0        0  ...
           3035                        1          0    0     0        0  ...
           3037                        1          0    0     0        0  ...

                     REAL                                                      \
                new-loose         new-slab         pwl-slab         wet-loose
                  lev_max lev_min  lev_max lev_min  lev_max lev_min   lev_max
2017-12-07 3003       0.0     0.0      0.0     0.0      0.0     0.0       0.0
           3007       0.0     0.0      0.0     0.0    700.0   200.0       0.0
           3009       0.0     0.0      0.0     0.0    700.0   200.0       0.0
           3010       0.0     0.0      0.0     0.0    700.0   200.0       0.0
           3011       0.0     0.0      0.0     0.0    700.0   200.0       0.0
...                   ...     ...      ...     ...      ...     ...       ...
2021-01-12 3031       0.0     0.0      0.0     0.0    600.0   600.0       0.0
           3032       0.0     0.0      0.0     0.0    800.0   800.0       0.0
           3034       0.0     0.0      0.0     0.0    600.0   600.0       0.0
           3035       0.0     0.0      0.0     0.0    800.0   800.0       0.0
           3037       0.0     0.0      0.0     0.0    800.0   800.0       0.0


                        wet-slab
                lev_min  lev_max lev_min
2017-12-07 3003     0.0      0.0     0.0
           3007     0.0      0.0     0.0
           3009     0.0      0.0     0.0
           3010     0.0      0.0     0.0
           3011     0.0      0.0     0.0
...                 ...      ...     ...
2021-01-12 3031     0.0      0.0     0.0
           3032     0.0      0.0     0.0
           3034     0.0      0.0     0.0
           3035     0.0      0.0     0.0
           3037     0.0      0.0     0.0

[12651 rows x 69 columns]

In [7]:
labeled_data.data.head()

                region_id_3001 region_id_3002 region_id_3003 region_id_3004  \
                             0              0              0              0
2017-12-07 3003            0.0            0.0            1.0            0.0
           3007            0.0            0.0            0.0            0.0
           3009            0.0            0.0            0.0            0.0
           3010            0.0            0.0            0.0            0.0
           3011            0.0            0.0            0.0            0.0

                region_id_3005 region_id_3006 region_id_3007 region_id_3008  \
                             0              0              0              0
2017-12-07 3003            0.0            0.0            0.0            0.0
           3007            0.0            0.0            1.0            0.0
           3009            0.0            0.0            0.0            0.0
           3010            0.0            0.0            0.0            0.0
           3011            0.0            0.0            0.0            0.0

                region_id_3009 region_id_3010  ... regobs_snowprofile_t_min_4  \
                             0              0  ...                          4
2017-12-07 3003            0.0            0.0  ...                        0.0
           3007            0.0            0.0  ...                        0.0
           3009            1.0            0.0  ...                        0.0
           3010            0.0            1.0  ...                        0.0
           3011            0.0            0.0  ...                        0.0

                               accuracy
                   5    6    7        2    3    4    5    6    7
2017-12-07 3003  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
           3007  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
           3009  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
           3010  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0
           3011  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 6562 columns]

In [8]:
labeled_data.data.shape

(12651, 6562)

In [9]:
labeled_data.data.index

MultiIndex([('2017-12-07', 3003),
            ('2017-12-07', 3007),
            ('2017-12-07', 3009),
            ('2017-12-07', 3010),
            ('2017-12-07', 3011),
            ('2017-12-07', 3012),
            ('2017-12-07', 3013),
            ('2017-12-07', 3014),
            ('2017-12-07', 3015),
            ('2017-12-07', 3016),
            ...
            ('2021-01-12', 3023),
            ('2021-01-12', 3024),
            ('2021-01-12', 3027),
            ('2021-01-12', 3028),
            ('2021-01-12', 3029),
            ('2021-01-12', 3031),
            ('2021-01-12', 3032),
            ('2021-01-12', 3034),
            ('2021-01-12', 3035),
            ('2021-01-12', 3037)],
           length=12651)

In [10]:
# get first level index, date
labeled_data.data.index.get_level_values(0)

Index(['2017-12-07', '2017-12-07', '2017-12-07', '2017-12-07', '2017-12-07',
       '2017-12-07', '2017-12-07', '2017-12-07', '2017-12-07', '2017-12-07',
       ...
       '2021-01-12', '2021-01-12', '2021-01-12', '2021-01-12', '2021-01-12',
       '2021-01-12', '2021-01-12', '2021-01-12', '2021-01-12', '2021-01-12'],
      dtype='object', length=12651)

In [11]:
# get second level index, region
labeled_data.data.index.get_level_values(1)

Int64Index([3003, 3007, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016,
            ...
            3023, 3024, 3027, 3028, 3029, 3031, 3032, 3034, 3035, 3037],
           dtype='int64', length=12651)

### Clustering data by region and time

I am interested in understanding how certain input variables are correlated to the output variables of interest. This includes how different snow pack conditions vary with avlanche problems and danger level warnings, but also how these input and output variables change with time, across different regions, etc.

The data is formatted as a MultiIndex in Pandas. This means we can first subset by time, then by region ID.

In [12]:
# look at df from one day
labeled_data.data.loc['2017-12-07'].shape

(21, 6562)

In [13]:
labeled_data.data.loc['2017-12-07']

     region_id_3001 region_id_3002 region_id_3003 region_id_3004  \
                  0              0              0              0
3003            0.0            0.0            1.0            0.0
3007            0.0            0.0            0.0            0.0
3009            0.0            0.0            0.0            0.0
3010            0.0            0.0            0.0            0.0
3011            0.0            0.0            0.0            0.0
3012            0.0            0.0            0.0            0.0
3013            0.0            0.0            0.0            0.0
3014            0.0            0.0            0.0            0.0
3015            0.0            0.0            0.0            0.0
3016            0.0            0.0            0.0            0.0
3017            0.0            0.0            0.0            0.0
3022            0.0            0.0            0.0            0.0
3023            0.0            0.0            0.0            0.0
3024            0.0            0.0            0.0            0.0
3027            0.0            0.0            0.0            0.0
3028            0.0            0.0            0.0            0.0
3029            0.0            0.0            0.0            0.0
3031            0.0            0.0            0.0            0.0
3032            0.0            0.0            0.0            0.0
3034            0.0            0.0            0.0            0.0
3035            0.0            0.0            0.0            0.0

     region_id_3005 region_id_3006 region_id_3007 region_id_3008  \
                  0              0              0              0
3003            0.0            0.0            0.0            0.0
3007            0.0            0.0            1.0            0.0
3009            0.0            0.0            0.0            0.0
3010            0.0            0.0            0.0            0.0
3011            0.0            0.0            0.0            0.0
3012            0.0            0.0            0.0            0.0
3013            0.0            0.0            0.0            0.0
3014            0.0            0.0            0.0            0.0
3015            0.0            0.0            0.0            0.0
3016            0.0            0.0            0.0            0.0
3017            0.0            0.0            0.0            0.0
3022            0.0            0.0            0.0            0.0
3023            0.0            0.0            0.0            0.0
3024            0.0            0.0            0.0            0.0
3027            0.0            0.0            0.0            0.0
3028            0.0            0.0            0.0            0.0
3029            0.0            0.0            0.0            0.0
3031            0.0            0.0            0.0            0.0
3032            0.0            0.0            0.0            0.0
3034            0.0            0.0            0.0            0.0
3035            0.0            0.0            0.0            0.0

     region_id_3009 region_id_3010  ... regobs_snowprofile_t_min_4            \
                  0              0  ...                          4    5    6
3003            0.0            0.0  ...                        0.0  0.0  0.0
3007            0.0            0.0  ...                        0.0  0.0  0.0
3009            1.0            0.0  ...                        0.0  0.0  0.0
3010            0.0            1.0  ...                        0.0  0.0  0.0
3011            0.0            0.0  ...                        0.0  0.0  0.0
3012            0.0            0.0  ...                        0.0  0.0  0.0
3013            0.0            0.0  ...                        0.0  0.0  0.0
3014            0.0            0.0  ...                        0.0  0.0  0.0
3015            0.0            0.0  ...                        0.0  0.0  0.0
3016            0.0            0.0  ...                        0.0  0.0  0.0
3017            0.0            0.0  ...                        0.0  0.0  0.0
3022            0.0            0.0  ...                        0.0  0.0  0.0
3023            0.0            0.0  ...                        0.0  0.0  0.0
3024            0.0            0.0  ...                        0.0  0.0  0.0
3027            0.0            0.0  ...                        0.0  0.0  0.0
3028            0.0            0.0  ...                        0.0  0.0  0.0
3029            0.0            0.0  ...                        0.0  0.0  0.0
3031            0.0            0.0  ...                        0.0  0.0  0.0
3032            0.0            0.0  ...                        0.0  0.0  0.0
3034            0.0            0.0  ...                        0.0  0.0  0.0
3035            0.0            0.0  ...                        0.0  0.0  0.0

          accuracy
        7        2    3    4    5    6    7
3003  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3007  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3009  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3010  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3011  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3012  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3013  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3014  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3015  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3016  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3017  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3022  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3023  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3024  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3027  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3028  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3029  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3031  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3032  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3034  0.0      0.0  0.0  0.0  0.0  0.0  0.0
3035  0.0      0.0  0.0  0.0  0.0  0.0  0.0

[21 rows x 6562 columns]

In [14]:
# now subset by day and region
labeled_data.data.loc['2017-12-07', 3003]

region_id_3001  0    0.0
region_id_3002  0    0.0
region_id_3003  0    1.0
region_id_3004  0    0.0
region_id_3005  0    0.0
                    ...
accuracy        3    0.0
                4    0.0
                5    0.0
                6    0.0
                7    0.0
Name: (2017-12-07, 3003), Length: 6562, dtype: float64

**Does the `LabeledData` class have a method that will drop extra region columns (`region_id_3001`, for example) and just get the columns of that pertain to the region of interest?**

In [15]:
# first, rename indices
labeled_data.data = labeled_data.data.rename_axis(['date','region'])

In [16]:
labeled_data.data

                  region_id_3001 region_id_3002 region_id_3003 region_id_3004  \
                               0              0              0              0
date       region
2017-12-07 3003              0.0            0.0            1.0            0.0
           3007              0.0            0.0            0.0            0.0
           3009              0.0            0.0            0.0            0.0
           3010              0.0            0.0            0.0            0.0
           3011              0.0            0.0            0.0            0.0
...                          ...            ...            ...            ...
2021-01-12 3031              0.0            0.0            0.0            0.0
           3032              0.0            0.0            0.0            0.0
           3034              0.0            0.0            0.0            0.0
           3035              0.0            0.0            0.0            0.0
           3037              0.0            0.0            0.0            0.0

                  region_id_3005 region_id_3006 region_id_3007 region_id_3008  \
                               0              0              0              0
date       region
2017-12-07 3003              0.0            0.0            0.0            0.0
           3007              0.0            0.0            1.0            0.0
           3009              0.0            0.0            0.0            0.0
           3010              0.0            0.0            0.0            0.0
           3011              0.0            0.0            0.0            0.0
...                          ...            ...            ...            ...
2021-01-12 3031              0.0            0.0            0.0            0.0
           3032              0.0            0.0            0.0            0.0
           3034              0.0            0.0            0.0            0.0
           3035              0.0            0.0            0.0            0.0
           3037              0.0            0.0            0.0            0.0

                  region_id_3009 region_id_3010  ...  \
                               0              0  ...
date       region                                ...
2017-12-07 3003              0.0            0.0  ...
           3007              0.0            0.0  ...
           3009              1.0            0.0  ...
           3010              0.0            1.0  ...
           3011              0.0            0.0  ...
...                          ...            ...  ...
2021-01-12 3031              0.0            0.0  ...
           3032              0.0            0.0  ...
           3034              0.0            0.0  ...
           3035              0.0            0.0  ...
           3037              0.0            0.0  ...

                  regobs_snowprofile_t_min_4                accuracy       \
                                           4    5    6    7        2    3
date       region
2017-12-07 3003                          0.0  0.0  0.0  0.0      0.0  0.0
           3007                          0.0  0.0  0.0  0.0      0.0  0.0
           3009                          0.0  0.0  0.0  0.0      0.0  0.0
           3010                          0.0  0.0  0.0  0.0      0.0  0.0
           3011                          0.0  0.0  0.0  0.0      0.0  0.0
...                                      ...  ...  ...  ...      ...  ...
2021-01-12 3031                          0.0  0.0  0.0  0.0      0.0  0.0
           3032                          0.0  0.0  0.0  0.0      0.0  0.0
           3034                          0.0  0.0  0.0  0.0      0.0  0.0
           3035                          0.0  0.0  0.0  0.0      0.0  0.0
           3037                          0.0  0.0  0.0  0.0      0.0  0.0


                     4    5    6    7
date       region
2017-12-07 3003    0.0  0.0  0.0  0.0
           3007    0.0  0.0  0.0  0.0
           3009    0.0  0.0  0.0  0.0
           3010    0.0  0.0  0.0  0.0
           3011    0.0  0.0  0.0  0.0
...                ...  ...  ...  ...
2021-01-12 3031    0.0  0.0  0.0  0.0
           3032    0.0  0.0  0.0  0.0
           3034    0.0  0.0  0.0  0.0
           3035    0.0  0.0  0.0  0.0
           3037    0.0  0.0  0.0  0.0

[12651 rows x 6562 columns]

In [17]:
# try to groupby hierarchical index
labeled_data.data.groupby(['region']).groups

{3003: MultiIndex([('2017-12-07', 3003),
             ('2017-12-08', 3003),
             ('2017-12-09', 3003),
             ('2017-12-10', 3003),
             ('2017-12-11', 3003),
             ('2017-12-12', 3003),
             ('2017-12-13', 3003),
             ('2017-12-14', 3003),
             ('2017-12-15', 3003),
             ('2017-12-16', 3003),
             ...
             ('2021-01-03', 3003),
             ('2021-01-04', 3003),
             ('2021-01-05', 3003),
             ('2021-01-06', 3003),
             ('2021-01-07', 3003),
             ('2021-01-08', 3003),
             ('2021-01-09', 3003),
             ('2021-01-10', 3003),
             ('2021-01-11', 3003),
             ('2021-01-12', 3003)],
            names=['date', 'region'], length=568),
 3006: MultiIndex([('2018-04-01', 3006),
             ('2020-02-13', 3006),
             ('2020-02-14', 3006),
             ('2020-02-15', 3006),
             ('2020-02-16', 3006),
             ('2020-02-17', 3006),
             ('2020-02-18', 3006),
             ('2020-02-19', 3006),
             ('2020-02-20', 3006),
             ('2020-02-21', 3006),
             ...
             ('2021-01-03', 3006),
             ('2021-01-04', 3006),
             ('2021-01-05', 3006),
             ('2021-01-06', 3006),
             ('2021-01-07', 3006),
             ('2021-01-08', 3006),
             ('2021-01-09', 3006),
             ('2021-01-10', 3006),
             ('2021-01-11', 3006),
             ('2021-01-12', 3006)],
            names=['date', 'region'], length=161),
 3007: MultiIndex([('2017-12-07', 3007),
             ('2017-12-08', 3007),
             ('2017-12-09', 3007),
             ('2017-12-10', 3007),
             ('2017-12-11', 3007),
             ('2017-12-12', 3007),
             ('2017-12-13', 3007),
             ('2017-12-14', 3007),
             ('2017-12-15', 3007),
             ('2017-12-16', 3007),
             ...
             ('2021-01-03', 3007),
             ('2021-01-04', 3007),
             ('2021-01-05', 3007),
             ('2021-01-06', 3007),
             ('2021-01-07', 3007),
             ('2021-01-08', 3007),
             ('2021-01-09', 3007),
             ('2021-01-10', 3007),
             ('2021-01-11', 3007),
             ('2021-01-12', 3007)],
            names=['date', 'region'], length=580),
 3009: MultiIndex([('2017-12-07', 3009),
             ('2017-12-08', 3009),
             ('2017-12-09', 3009),
             ('2017-12-10', 3009),
             ('2017-12-11', 3009),
             ('2017-12-12', 3009),
             ('2017-12-13', 3009),
             ('2017-12-14', 3009),
             ('2017-12-15', 3009),
             ('2017-12-16', 3009),
             ...
             ('2021-01-03', 3009),
             ('2021-01-04', 3009),
             ('2021-01-05', 3009),
             ('2021-01-06', 3009),
             ('2021-01-07', 3009),
             ('2021-01-08', 3009),
             ('2021-01-09', 3009),
             ('2021-01-10', 3009),
             ('2021-01-11', 3009),
             ('2021-01-12', 3009)],
            names=['date', 'region'], length=580),
 3010: MultiIndex([('2017-12-07', 3010),
             ('2017-12-08', 3010),
             ('2017-12-09', 3010),
             ('2017-12-10', 3010),
             ('2017-12-11', 3010),
             ('2017-12-12', 3010),
             ('2017-12-13', 3010),
             ('2017-12-14', 3010),
             ('2017-12-15', 3010),
             ('2017-12-16', 3010),
             ...
             ('2021-01-03', 3010),
             ('2021-01-04', 3010),
             ('2021-01-05', 3010),
             ('2021-01-06', 3010),
             ('2021-01-07', 3010),
             ('2021-01-08', 3010),
             ('2021-01-09', 3010),
             ('2021-01-10', 3010),
             ('2021-01-11', 3010),
             ('2021-01-12', 3010)],
            names=['date', 'region'], length=580),
 3011: MultiIndex([('2017-12-07', 3011),
             ('2017-12-08', 3011),
             ('2017-12-09', 3011),
             ('2017-12-10', 3011),
             ('2017-12-11', 3011),
             ('2017-12-12', 3011),
             ('2017-12-13', 3011),
             ('2017-12-14', 3011),
             ('2017-12-15', 3011),
             ('2017-12-16', 3011),
             ...
             ('2021-01-03', 3011),
             ('2021-01-04', 3011),
             ('2021-01-05', 3011),
             ('2021-01-06', 3011),
             ('2021-01-07', 3011),
             ('2021-01-08', 3011),
             ('2021-01-09', 3011),
             ('2021-01-10', 3011),
             ('2021-01-11', 3011),
             ('2021-01-12', 3011)],
            names=['date', 'region'], length=580),
 3012: MultiIndex([('2017-12-07', 3012),
             ('2017-12-08', 3012),
             ('2017-12-09', 3012),
             ('2017-12-10', 3012),
             ('2017-12-11', 3012),
             ('2017-12-12', 3012),
             ('2017-12-13', 3012),
             ('2017-12-14', 3012),
             ('2017-12-15', 3012),
             ('2017-12-16', 3012),
             ...
             ('2021-01-03', 3012),
             ('2021-01-04', 3012),
             ('2021-01-05', 3012),
             ('2021-01-06', 3012),
             ('2021-01-07', 3012),
             ('2021-01-08', 3012),
             ('2021-01-09', 3012),
             ('2021-01-10', 3012),
             ('2021-01-11', 3012),
             ('2021-01-12', 3012)],
            names=['date', 'region'], length=580),
 3013: MultiIndex([('2017-12-07', 3013),
             ('2017-12-08', 3013),
             ('2017-12-09', 3013),
             ('2017-12-10', 3013),
             ('2017-12-11', 3013),
             ('2017-12-12', 3013),
             ('2017-12-13', 3013),
             ('2017-12-14', 3013),
             ('2017-12-15', 3013),
             ('2017-12-16', 3013),
             ...
             ('2021-01-03', 3013),
             ('2021-01-04', 3013),
             ('2021-01-05', 3013),
             ('2021-01-06', 3013),
             ('2021-01-07', 3013),
             ('2021-01-08', 3013),
             ('2021-01-09', 3013),
             ('2021-01-10', 3013),
             ('2021-01-11', 3013),
             ('2021-01-12', 3013)],
            names=['date', 'region'], length=580),
 3014: MultiIndex([('2017-12-07', 3014),
             ('2017-12-08', 3014),
             ('2017-12-09', 3014),
             ('2017-12-10', 3014),
             ('2017-12-11', 3014),
             ('2017-12-12', 3014),
             ('2017-12-13', 3014),
             ('2017-12-14', 3014),
             ('2017-12-15', 3014),
             ('2017-12-16', 3014),
             ...
             ('2021-01-03', 3014),
             ('2021-01-04', 3014),
             ('2021-01-05', 3014),
             ('2021-01-06', 3014),
             ('2021-01-07', 3014),
             ('2021-01-08', 3014),
             ('2021-01-09', 3014),
             ('2021-01-10', 3014),
             ('2021-01-11', 3014),
             ('2021-01-12', 3014)],
            names=['date', 'region'], length=580),
 3015: MultiIndex([('2017-12-07', 3015),
             ('2017-12-08', 3015),
             ('2017-12-09', 3015),
             ('2017-12-10', 3015),
             ('2017-12-11', 3015),
             ('2017-12-12', 3015),
             ('2017-12-13', 3015),
             ('2017-12-14', 3015),
             ('2017-12-15', 3015),
             ('2017-12-16', 3015),
             ...
             ('2021-01-03', 3015),
             ('2021-01-04', 3015),
             ('2021-01-05', 3015),
             ('2021-01-06', 3015),
             ('2021-01-07', 3015),
             ('2021-01-08', 3015),
             ('2021-01-09', 3015),
             ('2021-01-10', 3015),
             ('2021-01-11', 3015),
             ('2021-01-12', 3015)],
            names=['date', 'region'], length=573),
 3016: MultiIndex([('2017-12-07', 3016),
             ('2017-12-08', 3016),
             ('2017-12-09', 3016),
             ('2017-12-10', 3016),
             ('2017-12-11', 3016),
             ('2017-12-12', 3016),
             ('2017-12-13', 3016),
             ('2017-12-14', 3016),
             ('2017-12-15', 3016),
             ('2017-12-16', 3016),
             ...
             ('2021-01-03', 3016),
             ('2021-01-04', 3016),
             ('2021-01-05', 3016),
             ('2021-01-06', 3016),
             ('2021-01-07', 3016),
             ('2021-01-08', 3016),
             ('2021-01-09', 3016),
             ('2021-01-10', 3016),
             ('2021-01-11', 3016),
             ('2021-01-12', 3016)],
            names=['date', 'region'], length=580),
 3017: MultiIndex([('2017-12-07', 3017),
             ('2017-12-08', 3017),
             ('2017-12-09', 3017),
             ('2017-12-10', 3017),
             ('2017-12-11', 3017),
             ('2017-12-12', 3017),
             ('2017-12-13', 3017),
             ('2017-12-14', 3017),
             ('2017-12-15', 3017),
             ('2017-12-16', 3017),
             ...
             ('2021-01-03', 3017),
             ('2021-01-04', 3017),
             ('2021-01-05', 3017),
             ('2021-01-06', 3017),
             ('2021-01-07', 3017),
             ('2021-01-08', 3017),
             ('2021-01-09', 3017),
             ('2021-01-10', 3017),
             ('2021-01-11', 3017),
             ('2021-01-12', 3017)],
            names=['date', 'region'], length=580),
 3022: MultiIndex([('2017-12-07', 3022),
             ('2017-12-08', 3022),
             ('2017-12-09', 3022),
             ('2017-12-10', 3022),
             ('2017-12-11', 3022),
             ('2017-12-12', 3022),
             ('2017-12-13', 3022),
             ('2017-12-14', 3022),
             ('2017-12-15', 3022),
             ('2017-12-16', 3022),
             ...
             ('2021-01-03', 3022),
             ('2021-01-04', 3022),
             ('2021-01-05', 3022),
             ('2021-01-06', 3022),
             ('2021-01-07', 3022),
             ('2021-01-08', 3022),
             ('2021-01-09', 3022),
             ('2021-01-10', 3022),
             ('2021-01-11', 3022),
             ('2021-01-12', 3022)],
            names=['date', 'region'], length=580),
 3023: MultiIndex([('2017-12-07', 3023),
             ('2017-12-08', 3023),
             ('2017-12-09', 3023),
             ('2017-12-10', 3023),
             ('2017-12-11', 3023),
             ('2017-12-12', 3023),
             ('2017-12-13', 3023),
             ('2017-12-14', 3023),
             ('2017-12-15', 3023),
             ('2017-12-16', 3023),
             ...
             ('2021-01-03', 3023),
             ('2021-01-04', 3023),
             ('2021-01-05', 3023),
             ('2021-01-06', 3023),
             ('2021-01-07', 3023),
             ('2021-01-08', 3023),
             ('2021-01-09', 3023),
             ('2021-01-10', 3023),
             ('2021-01-11', 3023),
             ('2021-01-12', 3023)],
            names=['date', 'region'], length=580),
 3024: MultiIndex([('2017-12-07', 3024),
             ('2017-12-08', 3024),
             ('2017-12-09', 3024),
             ('2017-12-10', 3024),
             ('2017-12-11', 3024),
             ('2017-12-12', 3024),
             ('2017-12-13', 3024),
             ('2017-12-14', 3024),
             ('2017-12-15', 3024),
             ('2017-12-16', 3024),
             ...
             ('2021-01-03', 3024),
             ('2021-01-04', 3024),
             ('2021-01-05', 3024),
             ('2021-01-06', 3024),
             ('2021-01-07', 3024),
             ('2021-01-08', 3024),
             ('2021-01-09', 3024),
             ('2021-01-10', 3024),
             ('2021-01-11', 3024),
             ('2021-01-12', 3024)],
            names=['date', 'region'], length=580),
 3027: MultiIndex([('2017-12-07', 3027),
             ('2017-12-08', 3027),
             ('2017-12-09', 3027),
             ('2017-12-10', 3027),
             ('2017-12-11', 3027),
             ('2017-12-12', 3027),
             ('2017-12-13', 3027),
             ('2017-12-14', 3027),
             ('2017-12-15', 3027),
             ('2017-12-16', 3027),
             ...
             ('2021-01-03', 3027),
             ('2021-01-04', 3027),
             ('2021-01-05', 3027),
             ('2021-01-06', 3027),
             ('2021-01-07', 3027),
             ('2021-01-08', 3027),
             ('2021-01-09', 3027),
             ('2021-01-10', 3027),
             ('2021-01-11', 3027),
             ('2021-01-12', 3027)],
            names=['date', 'region'], length=580),
 3028: MultiIndex([('2017-12-07', 3028),
             ('2017-12-08', 3028),
             ('2017-12-09', 3028),
             ('2017-12-10', 3028),
             ('2017-12-11', 3028),
             ('2017-12-12', 3028),
             ('2017-12-13', 3028),
             ('2017-12-14', 3028),
             ('2017-12-15', 3028),
             ('2017-12-16', 3028),
             ...
             ('2021-01-03', 3028),
             ('2021-01-04', 3028),
             ('2021-01-05', 3028),
             ('2021-01-06', 3028),
             ('2021-01-07', 3028),
             ('2021-01-08', 3028),
             ('2021-01-09', 3028),
             ('2021-01-10', 3028),
             ('2021-01-11', 3028),
             ('2021-01-12', 3028)],
            names=['date', 'region'], length=580),
 3029: MultiIndex([('2017-12-07', 3029),
             ('2017-12-08', 3029),
             ('2017-12-09', 3029),
             ('2017-12-10', 3029),
             ('2017-12-11', 3029),
             ('2017-12-12', 3029),
             ('2017-12-13', 3029),
             ('2017-12-14', 3029),
             ('2017-12-15', 3029),
             ('2017-12-16', 3029),
             ...
             ('2021-01-03', 3029),
             ('2021-01-04', 3029),
             ('2021-01-05', 3029),
             ('2021-01-06', 3029),
             ('2021-01-07', 3029),
             ('2021-01-08', 3029),
             ('2021-01-09', 3029),
             ('2021-01-10', 3029),
             ('2021-01-11', 3029),
             ('2021-01-12', 3029)],
            names=['date', 'region'], length=580),
 3031: MultiIndex([('2017-12-07', 3031),
             ('2017-12-08', 3031),
             ('2017-12-09', 3031),
             ('2017-12-10', 3031),
             ('2017-12-11', 3031),
             ('2017-12-12', 3031),
             ('2017-12-13', 3031),
             ('2017-12-14', 3031),
             ('2017-12-15', 3031),
             ('2017-12-16', 3031),
             ...
             ('2021-01-03', 3031),
             ('2021-01-04', 3031),
             ('2021-01-05', 3031),
             ('2021-01-06', 3031),
             ('2021-01-07', 3031),
             ('2021-01-08', 3031),
             ('2021-01-09', 3031),
             ('2021-01-10', 3031),
             ('2021-01-11', 3031),
             ('2021-01-12', 3031)],
            names=['date', 'region'], length=580),
 3032: MultiIndex([('2017-12-07', 3032),
             ('2017-12-08', 3032),
             ('2017-12-09', 3032),
             ('2017-12-10', 3032),
             ('2017-12-11', 3032),
             ('2017-12-12', 3032),
             ('2017-12-13', 3032),
             ('2017-12-14', 3032),
             ('2017-12-15', 3032),
             ('2017-12-16', 3032),
             ...
             ('2021-01-03', 3032),
             ('2021-01-04', 3032),
             ('2021-01-05', 3032),
             ('2021-01-06', 3032),
             ('2021-01-07', 3032),
             ('2021-01-08', 3032),
             ('2021-01-09', 3032),
             ('2021-01-10', 3032),
             ('2021-01-11', 3032),
             ('2021-01-12', 3032)],
            names=['date', 'region'], length=580),
 3034: MultiIndex([('2017-12-07', 3034),
             ('2017-12-08', 3034),
             ('2017-12-09', 3034),
             ('2017-12-10', 3034),
             ('2017-12-11', 3034),
             ('2017-12-12', 3034),
             ('2017-12-13', 3034),
             ('2017-12-14', 3034),
             ('2017-12-15', 3034),
             ('2017-12-16', 3034),
             ...
             ('2021-01-03', 3034),
             ('2021-01-04', 3034),
             ('2021-01-05', 3034),
             ('2021-01-06', 3034),
             ('2021-01-07', 3034),
             ('2021-01-08', 3034),
             ('2021-01-09', 3034),
             ('2021-01-10', 3034),
             ('2021-01-11', 3034),
             ('2021-01-12', 3034)],
            names=['date', 'region'], length=580),
 3035: MultiIndex([('2017-12-07', 3035),
             ('2017-12-08', 3035),
             ('2017-12-09', 3035),
             ('2017-12-10', 3035),
             ('2017-12-11', 3035),
             ('2017-12-12', 3035),
             ('2017-12-13', 3035),
             ('2017-12-14', 3035),
             ('2017-12-15', 3035),
             ('2017-12-16', 3035),
             ...
             ('2021-01-03', 3035),
             ('2021-01-04', 3035),
             ('2021-01-05', 3035),
             ('2021-01-06', 3035),
             ('2021-01-07', 3035),
             ('2021-01-08', 3035),
             ('2021-01-09', 3035),
             ('2021-01-10', 3035),
             ('2021-01-11', 3035),
             ('2021-01-12', 3035)],
            names=['date', 'region'], length=580),
 3037: MultiIndex([('2019-02-20', 3037),
             ('2019-02-21', 3037),
             ('2019-02-22', 3037),
             ('2019-02-23', 3037),
             ('2019-02-24', 3037),
             ('2019-02-25', 3037),
             ('2019-02-26', 3037),
             ('2019-02-27', 3037),
             ('2019-02-28', 3037),
             ('2019-03-01', 3037),
             ...
             ('2021-01-03', 3037),
             ('2021-01-04', 3037),
             ('2021-01-05', 3037),
             ('2021-01-06', 3037),
             ('2021-01-07', 3037),
             ('2021-01-08', 3037),
             ('2021-01-09', 3037),
             ('2021-01-10', 3037),
             ('2021-01-11', 3037),
             ('2021-01-12', 3037)],
            names=['date', 'region'], length=329)}

In [18]:
labeled_data.data.groupby(['region']).groups[3003]

MultiIndex([('2017-12-07', 3003),
            ('2017-12-08', 3003),
            ('2017-12-09', 3003),
            ('2017-12-10', 3003),
            ('2017-12-11', 3003),
            ('2017-12-12', 3003),
            ('2017-12-13', 3003),
            ('2017-12-14', 3003),
            ('2017-12-15', 3003),
            ('2017-12-16', 3003),
            ...
            ('2021-01-03', 3003),
            ('2021-01-04', 3003),
            ('2021-01-05', 3003),
            ('2021-01-06', 3003),
            ('2021-01-07', 3003),
            ('2021-01-08', 3003),
            ('2021-01-09', 3003),
            ('2021-01-10', 3003),
            ('2021-01-11', 3003),
            ('2021-01-12', 3003)],
           names=['date', 'region'], length=568)

In [19]:
labeled_data.data.groupby(['region']).groups[3003].get_level_values(0)

Index(['2017-12-07', '2017-12-08', '2017-12-09', '2017-12-10', '2017-12-11',
       '2017-12-12', '2017-12-13', '2017-12-14', '2017-12-15', '2017-12-16',
       ...
       '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07',
       '2021-01-08', '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12'],
      dtype='object', name='date', length=568)

In [20]:
labeled_data.data.groupby(['region']).groups[3003]

MultiIndex([('2017-12-07', 3003),
            ('2017-12-08', 3003),
            ('2017-12-09', 3003),
            ('2017-12-10', 3003),
            ('2017-12-11', 3003),
            ('2017-12-12', 3003),
            ('2017-12-13', 3003),
            ('2017-12-14', 3003),
            ('2017-12-15', 3003),
            ('2017-12-16', 3003),
            ...
            ('2021-01-03', 3003),
            ('2021-01-04', 3003),
            ('2021-01-05', 3003),
            ('2021-01-06', 3003),
            ('2021-01-07', 3003),
            ('2021-01-08', 3003),
            ('2021-01-09', 3003),
            ('2021-01-10', 3003),
            ('2021-01-11', 3003),
            ('2021-01-12', 3003)],
           names=['date', 'region'], length=568)

In [21]:
labeled_data.data.groupby(['region']).groups[3003].loc['2017-12-07']

AttributeError: 'MultiIndex' object has no attribute 'loc'

**The above seems to be working now, although I don't see any of the other column names. Has the other data now disappeared because I'm not somehow aggregating over the new groups (.sum(), .mean(), etc.)? Also, I can't seem to be able to access this new Multiindex object.**

# Make plots

I may need to normalize the input variables before I make the plots.